global:
  deploymentMode: development

name: pgadmin

pgadmin:
  image: dpage/pgadmin4:6.18
  user:
    login: admin@epam.com
    password: qwerty
  db:
    host: citus-master
    port: 5432

ingress:
  enabled: true
  annotations: {}
  host: pgadmin-chart
  path: "/"
  tls: []

edpComponent:
  description: "Користувацький інтерфейс для перегляду даних та схеми моделі даних реєстру."
  displayName: "Веб-інтерфейс перегляду даних реєстру (pgAdmin)"
  operationalZone: "registry-administration-zone"