apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  login: {{ .Values.pgadmin.user.login | b64enc | quote }}
  password: {{ .Values.pgadmin.user.password | b64enc | quote }}